import {
    ClerkProvider,
    SignedOut,
    SignUp,
    SignedIn,
    SignOut,
    UserButton,
} from '@clerk/nextjs';
import './globals.css';
import { GlobalContextProvider } from '@/container/GlobalContext';
import Navbar from '@/components/Navbar';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    <SignedOut>
                        <div className="w-screen h-screen flex items-center justify-center">
                            <SignUp routing="hash" />
                        </div>
                    </SignedOut>
                    <SignedIn>
                        <GlobalContextProvider>
                            {children}
                            <Navbar />
                        </GlobalContextProvider>
                    </SignedIn>
                </body>
            </html>
        </ClerkProvider>
    );
}
