import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs';
import './globals.css';
import { GlobalContextProvider } from '@/container/GlobalContext';
import Navbar from '@/components/Navbar';
import Signup from '@/components/SignUp';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    <SignedOut>
                        <Signup />
                    </SignedOut>
                    <SignedIn>
                        <GlobalContextProvider>
                            {children}
                            <Navbar />
                        </GlobalContextProvider>
                    </SignedIn>
                </body>
            </html>
        </ClerkProvider>
    );
}
