import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import './globals.css'
import { GlobalContextProvider } from '@/container/GlobalContext';
import Navbar from '@/components/Navbar';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <GlobalContextProvider>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          {children}
          </GlobalContextProvider>
          <Navbar />
        </body>
      </html>
    </ClerkProvider>
  )
}
